### ISSUE TITLE
Broken light sources?

### ISSUE THREAD

**Issue by GotoFinal** [Ashok0/EnderalVR#1]
Hello, first: great job on the pack, thank you for creating this. I'm having one issue: many light sources, like torches in some caves, just don't give any light off, making exploring some places really hard, do you know what causes that and if it can be fixed? If i pickup such torch from wall and hold it myself it works just fine. But mane caves or building are very dark because of this. This can affect near any type of light source in game.

(Also why R.A.S.S in VR? it makes weird unnatural distortions when rain is active, but well, thats something i can remove on my own so)

**Comment by Ashok0** [comment]
Hi, 

I'm glad you found the  pack useful!  I'm not sure what the deal is with light sources.  I don't have a saved game in any dark dungeons at the moment, but if you can upload a saved game near torches in a dark cave I would love to look into this issue further.  In the meantime, I would recommend adding "Rally's Candlelight and Magelight Fix SE - VR" to your modlist as this seems to greatly help with illumination.  

I added R.A.S.S. to the modlist because it adds really nice snow effects to your VRIK hands during snowstorms.  I found this to really improve immersion in VR.  The only downside to the mod is the rain distortion, but this can be 100% disabled as noted in the documentation for the repack which seemed like a decent solution.

****EDIT****:  I have updated the repack with Rally's Candlelight and Magelight Fix and will close this issue for time being as this seems to help tremendously with lighting in dark environments.

**Comment by GotoFinal** [comment]
Thanks, that helps a bit but sad that im required to use additional lights even in places that are pretty light up, I might later try to upload some save in one of such places.
